name: Notes Application CI Pipeline
# create a CI pipeline based on the assignment specification
# remember to commit often

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

defaults:
  run:
    working-directory: src

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm clean-install
      - name: Run linter
        run: npm run test-lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm clean-install
      - name: Run unit tests
        run: npm run test-unit
  integration-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm clean-install
      - name: Run integration tests
        env:
          SERVER: mongodb://localhost:27017
        run: npm run test-integration

  end-to-end-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm clean-install
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Run server
        run: npm run start &
      - name: Run end-to-end tests
        env:
          SERVER: mongodb://localhost:27017
        run: npm run test-e2e
      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: src/playwright-report/

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js 18.x
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "18"
    # needs: [lint, unit-test, integration-test, end-to-end-test]
    # steps:
    #   - uses: actions/checkout@v3
    #   - name: Use Node.js 18.x
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: "18"
    #   - name: Install dependencies
    #   run: npm clean-install
    #   - name: Build artifact
    #   run: npm run build
    #   - name: Archive artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: my-app
    #     path: path/to/artifact
